[platformio]
default_envs = esp32c3_factory

[env:esp32c3_factory]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.flash_size = 4MB
board_build.partitions = partitions.csv
build_flags =
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
  -D GPSRING_FIRMWARE_VERSION=\"v0.3.3\"
  -D GPSRING_DEVICE_PREFIX=\"G0703\"
  -D GPSRING_WIFI_SSID=\"gscc\"
  -D GPSRING_WIFI_PASS=\"2965084522053\"
  -D GPSRING_OTA_HOST=\"192.168.120.218\"
  -D GPSRING_OTA_PORT=8802
